Repository peytonjo/Dad-Jokes, pull requests merged in 2021-01, with the labels that each got.

#1 Feature/api calls router
  .eslintcache
  src/ApiCalls.js
  src/App/App.js
  src/App/App.scss
  src/NavBar/NavBar.js
  src/NavBar/NavBar.scss
  src/User/User.js
  src/index.js
Labels: enhancement

#2 Features/functionality and testing
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/examples/App_spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
  src/App/App.js
  src/App/App.test.js
  src/Form/Form.js
  src/Form/Form.scss
  src/NavBar/NavBar.js
  src/RandomJoke/RandomJoke.js
  src/RandomJoke/RandomJoke.scss
  src/RandomJoke/RandomJoke.test.js
  src/User/User.js
  src/index.js
Labels: enhancement

#3 Feature/testing
  .eslintcache
  cypress/integration/examples/App_spec.js
  src/App/App.test.js
  src/NavBar/NavBar.js
  src/NavBar/NavBar.test.js
  src/User/User.js
  src/cypress.js
Labels: TDD

#4 Feature/new joke form
  .eslintcache
  src/CreatedCard/CreatedCard.js
  src/Form/Form.js
  src/RandomJoke/RandomJoke.js
  src/User/User.js
  src/User/User.scss
Labels: enhancement

#5 Feature/unit tests
  .eslintcache
  package-lock.json
  package.json
  src/App/App.test.js
  src/CreatedCard/CreatedCard.js
  src/CreatedCard/CreatedCard.scss
  src/CreatedCard/CreatedCard.test.js
  src/Form/Form.test.js
  src/NavBar/NavBar.test.js
  src/RandomJoke/RandomJoke.js
  src/RandomJoke/RandomJoke.test.js
  src/User/User.js
  src/User/User.test.js
  src/docs/pull_request_template.md
  src/localStorage.js
Labels: TDD

#6 Feature/integration testing
  .eslintcache
  cypress/integration/examples/App_spec.js
  docs/pull_request_template.md
  src/App/App.test.js
  src/Form/Form.js
  src/Form/Form.test.js
  src/NavBar/NavBar.test.js
Labels: TDD

#7 Fix/clean up
  .eslintcache
  public/logo192.png
  public/logo512.png
  src/ApiCalls.js
  src/App/App.js
  src/App/App.scss
  src/CreatedCard/CreatedCard.js
  src/CreatedCard/CreatedCard.scss
  src/Form/Form.js
  src/Form/Form.scss
  src/NavBar/NavBar.js
  src/NavBar/NavBar.scss
  src/RandomJoke/RandomJoke.scss
  src/User/User.js
  src/User/User.scss
  src/colors.scss
Labels: SCSS, TDD
